name: Build Box3D (Windows)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Configure CMake
      run: cmake -B build -G "Visual Studio 17 2022" -A x64

    - name: Build Box3D Samples
      run: cmake --build build --config Release

    - name: Prepare Artifacts
      shell: powershell
      run: |
        New-Item -ItemType Directory -Force -Path export_build
        Copy-Item -Path "build\bin\Release\samples.exe" -Destination "export_build\"
        Copy-Item -Path "build\bin\Release\*.dll" -Destination "export_build\" -ErrorAction Silently Continue

    - name: Upload Exported Windows Executables
      uses: actions/upload-artifact@v5
      with:
        name: box3d-windows-x64
        path: export_build/
